Guedes#11
AGES-PUCRS/mase-auth-service pull request #12
Opened 2019-06-07 23:18 UTC by guedes4g

2019-06-07 23:42 UTC, rafaritter44 requested changes

2019-06-07 23:42 UTC, rafaritter44 commented on mase-authservice.postman_collection.json
> +{
Remover esse arquivo.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/api/AuthController.java
> +@RestController
Colocar @RequestMapping com URI padrão /api/auth.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/api/AuthController.java
> +			System.out.println("ERROR");
Remover esse print.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/api/RegisterController.java
> +@RestController
Criar @RequestMapping com URI padrão.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/model/Auth.java
> +public class Auth {
Criar um nome mais descritivo.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/dto/AuthRequestDto.java
> +public class AuthRequestDto {
Colocar um nome mais significativo. Exemplo: LoginRequestDto.

2019-06-07 23:42 UTC, rafaritter44 commented on src/main/java/br/pucrs/ages/mase/authservice/dto/AuthResponseDto.java
> +public class AuthResponseDto {
Colocar um nome mais significativo.

2019-06-08 00:35 UTC, guedes4g commented on mase-authservice.postman_collection.json
> +{
nao

2019-06-08 00:36 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/api/AuthController.java
> +			System.out.println("ERROR");
Melhor println que ja vi

2019-06-08 00:37 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/api/RegisterController.java
> +@RestController
Nope

2019-06-08 00:37 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/model/Auth.java
> +public class Auth {
Ja descreve bem

2019-06-08 00:37 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/dto/AuthRequestDto.java
> +public class AuthRequestDto {
Deu de requisiçoes de nomenclatura, nao atrapalha o andamento mais

2019-06-08 00:37 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/dto/AuthResponseDto.java
> +public class AuthResponseDto {
Deu de requisiçoes de nomenclatura, nao atrapalha o andamento mais

2019-06-08 00:38 UTC, guedes4g commented on src/main/java/br/pucrs/ages/mase/authservice/dto/AuthResponseDto.java
> +public class AuthResponseDto {
Arruda já requisitou que parasse com esse tipo de requisição

2019-06-15 00:27 UTC, ViniKroth approved these changes

2019-06-15 00:33 UTC, merged